name: AWS R/Start Labs Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0
      - name: Install Dependencies
        run: npm install
      - name: Code Format
        run: npm run format

  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0
      - name: Clear npm cache
        run: npm cache clean -f
      - name: Delete node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: Start app
        run: npm run dev
      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v6.4.0
        with:
          start: npm run dev
          wait-on: "http://localhost:3000"
          browser: electron
          config-file: cypress.config.ts

  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
